"""Add api_keys table

Revision ID: 70212c3f5490
Revises: bc99a100eeb0
Create Date: 2025-11-07 12:04:02.080111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70212c3f5490'
down_revision: Union[str, Sequence[str], None] = 'bc99a100eeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='api_key_status'), server_default='active', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_account_id'), 'api_keys', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=True)
    op.drop_index(op.f('idx_game_created_at_desc'), table_name='game')
    op.drop_index(op.f('idx_game_deleted_at'), table_name='game', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_game_hex_id'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('idx_score_deleted_at'), table_name='score', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_score_game_date_desc'), table_name='score', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_score_game_score_desc'), table_name='score', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_score_game_user_asc'), table_name='score', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_score_user_id'), table_name='score', postgresql_where='(deleted_at IS NULL)')
    op.drop_table('score')
    op.drop_table('_sqlx_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_sqlx_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('checksum', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('_sqlx_migrations_pkey'))
    )
    op.create_table('score',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('game_hex_id', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('score', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score_val', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('extra', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('length(user_id::text) > 0 AND length(user_id::text) <= 255', name=op.f('score_user_id_check')),
    sa.CheckConstraint('length(user_name::text) > 0 AND length(user_name::text) <= 100', name=op.f('score_user_name_check')),
    sa.ForeignKeyConstraint(['game_hex_id'], ['game.hex_id'], name=op.f('score_game_hex_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('score_pkey'))
    )
    op.create_index(op.f('idx_score_user_id'), 'score', ['user_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_score_game_user_asc'), 'score', ['game_hex_id', sa.literal_column('lower(user_name::text)'), 'id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_score_game_score_desc'), 'score', ['game_hex_id', sa.literal_column('score_val DESC'), 'id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_score_game_date_desc'), 'score', ['game_hex_id', sa.literal_column('submitted_at DESC'), 'id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_score_deleted_at'), 'score', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('game',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('hex_id', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("hex_id::text ~ '^[0-9a-z]{6}$'::text", name=op.f('game_hex_id_check')),
    sa.CheckConstraint('length(name::text) > 0 AND length(name::text) <= 255', name=op.f('game_name_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('game_pkey')),
    sa.UniqueConstraint('hex_id', name=op.f('game_hex_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_game_hex_id'), 'game', ['hex_id'], unique=True)
    op.create_index(op.f('idx_game_deleted_at'), 'game', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_game_created_at_desc'), 'game', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_account_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
