"""Remove config_template from BoardTemplate

Revision ID: 38bede218bc4
Revises: 55a2fbfdefdc
Create Date: 2025-11-24 15:30:05.201444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38bede218bc4"
down_revision: str | Sequence[str] | None = "55a2fbfdefdc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("board_templates", "config_template")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "board_templates",
        sa.Column(
            "config_template",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
