"""remove scores_user_id_fkey

Revision ID: c5d1d5a67269
Revises: 9296c489fd00
Create Date: 2025-11-12 18:05:20.134459

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5d1d5a67269"
down_revision: str | Sequence[str] | None = "9296c489fd00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("scores_user_id_fkey"), "scores", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("scores_user_id_fkey"), "scores", "users", ["device_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
