"""Add Board fields to BoardTemplate as first-class columns

Revision ID: 55a2fbfdefdc
Revises: 726e176cad8a
Create Date: 2025-11-24 14:55:47.418973

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55a2fbfdefdc"
down_revision: str | Sequence[str] | None = "726e176cad8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("board_templates", sa.Column("slug", sa.String(), nullable=False))
    op.add_column("board_templates", sa.Column("icon", sa.String(), nullable=True))
    op.add_column("board_templates", sa.Column("unit", sa.String(), nullable=True))
    op.add_column("board_templates", sa.Column("sort_direction", sa.String(), nullable=False))
    op.add_column("board_templates", sa.Column("keep_strategy", sa.String(), nullable=False))
    op.add_column(
        "board_templates", sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "board_templates", sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "board_templates",
        sa.Column("tags", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("board_templates", "tags")
    op.drop_column("board_templates", "ends_at")
    op.drop_column("board_templates", "starts_at")
    op.drop_column("board_templates", "keep_strategy")
    op.drop_column("board_templates", "sort_direction")
    op.drop_column("board_templates", "unit")
    op.drop_column("board_templates", "icon")
    op.drop_column("board_templates", "slug")
    # ### end Alembic commands ###
