"""Make BoardTemplate slug nullable

Revision ID: baed777980ab
Revises: 38bede218bc4
Create Date: 2025-11-24 16:09:22.582324

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baed777980ab"
down_revision: str | Sequence[str] | None = "38bede218bc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("board_templates", "slug", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("board_templates", "slug", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
