"""Add unique constraint on BoardTemplate series per game

Revision ID: e5a3fd5cadf3
Revises: c909486f9060
Create Date: 2025-12-08 17:14:17.365777

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5a3fd5cadf3"
down_revision: str | Sequence[str] | None = "c909486f9060"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_board_template_game_series",
        "board_templates",
        ["game_id", "series"],
        unique=True,
        postgresql_where=sa.text("series IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_board_template_game_series",
        table_name="board_templates",
        postgresql_where=sa.text("series IS NOT NULL"),
    )
    # ### end Alembic commands ###
