"""add refresh token fields to device sessions

Revision ID: 1fa66d6f6b4b
Revises: bc1ad0d69fd6
Create Date: 2025-11-12 13:08:22.111950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa66d6f6b4b'
down_revision: Union[str, Sequence[str], None] = 'bc1ad0d69fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sessions', sa.Column('refresh_token_hash', sa.String(), nullable=False))
    op.add_column('device_sessions', sa.Column('token_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('device_sessions', sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_device_sessions_refresh_expires_at'), 'device_sessions', ['refresh_expires_at'], unique=False)
    op.create_index(op.f('ix_device_sessions_refresh_token_hash'), 'device_sessions', ['refresh_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_sessions_refresh_token_hash'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_refresh_expires_at'), table_name='device_sessions')
    op.drop_column('device_sessions', 'refresh_expires_at')
    op.drop_column('device_sessions', 'token_version')
    op.drop_column('device_sessions', 'refresh_token_hash')
    # ### end Alembic commands ###
