"""Add is_published column to boards and board_templates

Revision ID: 5d133d0d82fb
Revises: baed777980ab
Create Date: 2025-11-24 16:49:01.639141

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d133d0d82fb"
down_revision: str | Sequence[str] | None = "baed777980ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "board_templates",
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "boards",
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boards", "is_published")
    op.drop_column("board_templates", "is_published")
    # ### end Alembic commands ###
