"""Add tags and description to games

Revision ID: c75b317a3d22
Revises: e5a3fd5cadf3
Create Date: 2025-12-11 14:48:47.026858

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c75b317a3d22"
down_revision: str | Sequence[str] | None = "e5a3fd5cadf3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "games", sa.Column("tags", sa.ARRAY(sa.String()), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "tags")
    op.drop_column("games", "description")
    # ### end Alembic commands ###
