"""add user_id to api_keys

Revision ID: dc2ab243348c
Revises: 2a37ba44ac19
Create Date: 2025-11-13 09:12:43.673831

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc2ab243348c"
down_revision: str | Sequence[str] | None = "2a37ba44ac19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_foreign_key(None, "api_keys", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_keys", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_column("api_keys", "user_id")
    # ### end Alembic commands ###
