"""add nonces table for replay protection

Revision ID: 73540480ef92
Revises: 1fa66d6f6b4b
Create Date: 2025-11-12 13:54:41.658810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73540480ef92'
down_revision: Union[str, Sequence[str], None] = '1fa66d6f6b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonces',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('nonce_value', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'used', 'expired', name='nonce_status'), server_default='pending', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nonces_device_id'), 'nonces', ['device_id'], unique=False)
    op.create_index(op.f('ix_nonces_expires_at'), 'nonces', ['expires_at'], unique=False)
    op.create_index(op.f('ix_nonces_nonce_value'), 'nonces', ['nonce_value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nonces_nonce_value'), table_name='nonces')
    op.drop_index(op.f('ix_nonces_expires_at'), table_name='nonces')
    op.drop_index(op.f('ix_nonces_device_id'), table_name='nonces')
    op.drop_table('nonces')
    # ### end Alembic commands ###
