"""Add page_url to games

Revision ID: 8d64722e3661
Revises: c75b317a3d22
Create Date: 2025-12-11 14:54:38.220866

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d64722e3661"
down_revision: str | Sequence[str] | None = "c75b317a3d22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("page_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "page_url")
    # ### end Alembic commands ###
