"""add devices and device_sessions tables

Revision ID: 4de10168f638
Revises: e39a80493d94
Create Date: 2025-11-11 18:33:33.532727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de10168f638'
down_revision: Union[str, Sequence[str], None] = 'e39a80493d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'banned', 'suspended', name='device_status'), server_default='active', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_account_id'), 'devices', ['account_id'], unique=False)
    op.create_index('ix_devices_game_device', 'devices', ['game_id', 'device_id'], unique=True)
    op.create_index(op.f('ix_devices_game_id'), 'devices', ['game_id'], unique=False)
    op.create_table('device_sessions',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('access_token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_sessions_access_token_hash'), 'device_sessions', ['access_token_hash'], unique=False)
    op.create_index(op.f('ix_device_sessions_device_id'), 'device_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_sessions_expires_at'), 'device_sessions', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_sessions_expires_at'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_device_id'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_access_token_hash'), table_name='device_sessions')
    op.drop_table('device_sessions')
    op.drop_index(op.f('ix_devices_game_id'), table_name='devices')
    op.drop_index('ix_devices_game_device', table_name='devices')
    op.drop_index(op.f('ix_devices_account_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
