"""add last_score_value to score_submission_metadata

Revision ID: b4d77c391fd8
Revises: f7c5f54c8e30
Create Date: 2025-11-12 15:23:56.685700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d77c391fd8'
down_revision: Union[str, Sequence[str], None] = 'f7c5f54c8e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_submission_metadata', sa.Column('last_score_value', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_score_submission_metadata_user_id'), table_name='score_submission_metadata')
    op.create_index(op.f('ix_score_submission_metadata_device_id'), 'score_submission_metadata', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_submission_metadata_device_id'), table_name='score_submission_metadata')
    op.create_index(op.f('ix_score_submission_metadata_user_id'), 'score_submission_metadata', ['device_id'], unique=False)
    op.drop_column('score_submission_metadata', 'last_score_value')
    # ### end Alembic commands ###
