"""Add soft delete to api keys

Revision ID: 63132b8795b5
Revises: 7d6e7dcb79c2
Create Date: 2025-11-07 16:19:27.853392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63132b8795b5'
down_revision: Union[str, Sequence[str], None] = '7d6e7dcb79c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'deleted_at')
    # ### end Alembic commands ###
