"""add super_admin field to users

Revision ID: 2a37ba44ac19
Revises: c5d1d5a67269
Create Date: 2025-11-12 19:57:03.459628

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a37ba44ac19"
down_revision: str | Sequence[str] | None = "c5d1d5a67269"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("super_admin", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "super_admin")
    # ### end Alembic commands ###
