"""add series to board templates and rename template_id

Revision ID: 420fd101ae71
Revises: 32e23fb2cb23
Create Date: 2025-11-17 17:17:14.350392

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "420fd101ae71"
down_revision: str | Sequence[str] | None = "32e23fb2cb23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("board_templates", sa.Column("series", sa.String(), nullable=True))
    op.add_column("boards", sa.Column("created_from_template_id", sa.Uuid(), nullable=True))
    op.drop_column("boards", "template_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boards", sa.Column("template_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column("boards", "created_from_template_id")
    op.drop_column("board_templates", "series")
    # ### end Alembic commands ###
