"""remove unique constraint from game name column

Revision ID: 93ff1903e86b
Revises: 47e86f46d73f
Create Date: 2025-11-24 12:23:27.419075

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93ff1903e86b"
down_revision: str | Sequence[str] | None = "47e86f46d73f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_boards_short_code"), "boards", ["short_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_boards_short_code"), table_name="boards")
    # ### end Alembic commands ###
