"""init

Revision ID: c909486f9060
Revises:
Create Date: 2025-11-24 17:37:42.890807

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c909486f9060"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="account_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_name"), "accounts", ["name"], unique=True)
    op.create_index(op.f("ix_accounts_slug"), "accounts", ["slug"], unique=True)
    op.create_table(
        "emails",
        sa.Column("to", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("from_email", sa.String(), nullable=True),
        sa.Column("reply_to", sa.String(), nullable=True),
        sa.Column("cc", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("bcc", sa.JSON(), server_default="[]", nullable=False),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "high", "urgent", name="email_priority"),
            server_default="normal",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "delivered", "failed", name="email_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("template_data", sa.JSON(), nullable=True),
        sa.Column("provider_message_id", sa.String(), nullable=True),
        sa.Column("provider_response", sa.JSON(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_emails_created_at", "emails", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_emails_provider_message_id"), "emails", ["provider_message_id"], unique=False
    )
    op.create_index(op.f("ix_emails_status"), "emails", ["status"], unique=False)
    op.create_index(op.f("ix_emails_to"), "emails", ["to"], unique=False)
    op.create_table(
        "jam_codes",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("features", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("current_uses", sa.Integer(), server_default="0", nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_jam_codes_active_expires", "jam_codes", ["active", "expires_at"], unique=False
    )
    op.create_index(op.f("ix_jam_codes_code"), "jam_codes", ["code"], unique=True)
    op.create_table(
        "verification_codes",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "used", "expired", name="verification_code_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_codes_email"), "verification_codes", ["email"], unique=False
    )
    op.create_index(
        "ix_verification_codes_email_status",
        "verification_codes",
        ["email", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_codes_expires_at"), "verification_codes", ["expires_at"], unique=False
    )
    op.create_table(
        "games",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("steam_app_id", sa.String(), nullable=True),
        sa.Column("default_board_id", sa.Uuid(), nullable=True),
        sa.Column("anti_cheat_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "name", name="uq_account_game_name"),
        sa.UniqueConstraint("slug", name="uq_game_slug"),
    )
    op.create_index(op.f("ix_games_account_id"), "games", ["account_id"], unique=False)
    op.create_index(op.f("ix_games_slug"), "games", ["slug"], unique=True)
    op.create_table(
        "jam_code_redemptions",
        sa.Column("jam_code_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("meta", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["jam_code_id"], ["jam_codes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jam_code_redemptions_account_id"),
        "jam_code_redemptions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "ix_jam_code_redemptions_jam_code_account",
        "jam_code_redemptions",
        ["jam_code_id", "account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jam_code_redemptions_jam_code_id"),
        "jam_code_redemptions",
        ["jam_code_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("super_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_account_id"), "users", ["account_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("key_prefix", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "revoked", name="api_key_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_account_id"), "api_keys", ["account_id"], unique=False)
    op.create_index(op.f("ix_api_keys_key_prefix"), "api_keys", ["key_prefix"], unique=True)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "board_templates",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("name_template", sa.String(), nullable=True),
        sa.Column("series", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("sort_direction", sa.String(), nullable=False),
        sa.Column("keep_strategy", sa.String(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("repeat_interval", sa.String(), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_board_templates_account_id"), "board_templates", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_board_templates_game_id"), "board_templates", ["game_id"], unique=False
    )
    op.create_table(
        "boards",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("short_code", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_direction", sa.String(), nullable=False),
        sa.Column("keep_strategy", sa.String(), nullable=False),
        sa.Column("created_from_template_id", sa.Uuid(), nullable=True),
        sa.Column("template_name", sa.String(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_code", name="uq_board_short_code"),
    )
    op.create_index(
        "ix_board_slug_unique_when_active",
        "boards",
        ["account_id", "game_id", "slug"],
        unique=True,
        postgresql_where="is_active = true",
    )
    op.create_index(op.f("ix_boards_account_id"), "boards", ["account_id"], unique=False)
    op.create_index(op.f("ix_boards_game_id"), "boards", ["game_id"], unique=False)
    op.create_index(op.f("ix_boards_short_code"), "boards", ["short_code"], unique=True)
    op.create_index(op.f("ix_boards_slug"), "boards", ["slug"], unique=False)
    op.create_table(
        "devices",
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("client_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "banned", "suspended", name="device_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_account_id"), "devices", ["account_id"], unique=False)
    op.create_index(
        "ix_devices_game_device", "devices", ["game_id", "client_fingerprint"], unique=True
    )
    op.create_index(op.f("ix_devices_game_id"), "devices", ["game_id"], unique=False)
    op.create_table(
        "device_sessions",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("access_token_hash", sa.String(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_sessions_access_token_hash"),
        "device_sessions",
        ["access_token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_sessions_device_id"), "device_sessions", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_device_sessions_expires_at"), "device_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_device_sessions_refresh_expires_at"),
        "device_sessions",
        ["refresh_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_sessions_refresh_token_hash"),
        "device_sessions",
        ["refresh_token_hash"],
        unique=False,
    )
    op.create_table(
        "nonces",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("nonce_value", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "used", "expired", name="nonce_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nonces_device_id"), "nonces", ["device_id"], unique=False)
    op.create_index(op.f("ix_nonces_expires_at"), "nonces", ["expires_at"], unique=False)
    op.create_index(op.f("ix_nonces_nonce_value"), "nonces", ["nonce_value"], unique=True)
    op.create_table(
        "scores",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("board_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("value_display", sa.String(), nullable=True),
        sa.Column("filter_timezone", sa.String(), nullable=True),
        sa.Column("filter_country", sa.String(), nullable=True),
        sa.Column("filter_city", sa.String(), nullable=True),
        sa.Column("score_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scores_account_id"), "scores", ["account_id"], unique=False)
    op.create_index(op.f("ix_scores_board_id"), "scores", ["board_id"], unique=False)
    op.create_index(op.f("ix_scores_device_id"), "scores", ["device_id"], unique=False)
    op.create_index(op.f("ix_scores_game_id"), "scores", ["game_id"], unique=False)
    op.create_table(
        "score_flags",
        sa.Column("score_id", sa.Uuid(), nullable=False),
        sa.Column("flag_type", sa.String(), nullable=False),
        sa.Column("confidence", sa.String(), nullable=False),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_decision", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["score_id"], ["scores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_score_flags_confidence"), "score_flags", ["confidence"], unique=False)
    op.create_index(op.f("ix_score_flags_flag_type"), "score_flags", ["flag_type"], unique=False)
    op.create_index(op.f("ix_score_flags_score_id"), "score_flags", ["score_id"], unique=False)
    op.create_index(op.f("ix_score_flags_status"), "score_flags", ["status"], unique=False)
    op.create_table(
        "score_submission_metadata",
        sa.Column("score_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("board_id", sa.Uuid(), nullable=False),
        sa.Column("submission_count", sa.Integer(), nullable=False),
        sa.Column("last_submission_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_score_value", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["score_id"], ["scores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_score_submission_metadata_board_id"),
        "score_submission_metadata",
        ["board_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_score_submission_metadata_device_id"),
        "score_submission_metadata",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_score_submission_metadata_score_id"),
        "score_submission_metadata",
        ["score_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_score_submission_metadata_score_id"), table_name="score_submission_metadata"
    )
    op.drop_index(
        op.f("ix_score_submission_metadata_device_id"), table_name="score_submission_metadata"
    )
    op.drop_index(
        op.f("ix_score_submission_metadata_board_id"), table_name="score_submission_metadata"
    )
    op.drop_table("score_submission_metadata")
    op.drop_index(op.f("ix_score_flags_status"), table_name="score_flags")
    op.drop_index(op.f("ix_score_flags_score_id"), table_name="score_flags")
    op.drop_index(op.f("ix_score_flags_flag_type"), table_name="score_flags")
    op.drop_index(op.f("ix_score_flags_confidence"), table_name="score_flags")
    op.drop_table("score_flags")
    op.drop_index(op.f("ix_scores_game_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_device_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_board_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_account_id"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_nonces_nonce_value"), table_name="nonces")
    op.drop_index(op.f("ix_nonces_expires_at"), table_name="nonces")
    op.drop_index(op.f("ix_nonces_device_id"), table_name="nonces")
    op.drop_table("nonces")
    op.drop_index(op.f("ix_device_sessions_refresh_token_hash"), table_name="device_sessions")
    op.drop_index(op.f("ix_device_sessions_refresh_expires_at"), table_name="device_sessions")
    op.drop_index(op.f("ix_device_sessions_expires_at"), table_name="device_sessions")
    op.drop_index(op.f("ix_device_sessions_device_id"), table_name="device_sessions")
    op.drop_index(op.f("ix_device_sessions_access_token_hash"), table_name="device_sessions")
    op.drop_table("device_sessions")
    op.drop_index(op.f("ix_devices_game_id"), table_name="devices")
    op.drop_index("ix_devices_game_device", table_name="devices")
    op.drop_index(op.f("ix_devices_account_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_boards_slug"), table_name="boards")
    op.drop_index(op.f("ix_boards_short_code"), table_name="boards")
    op.drop_index(op.f("ix_boards_game_id"), table_name="boards")
    op.drop_index(op.f("ix_boards_account_id"), table_name="boards")
    op.drop_index(
        "ix_board_slug_unique_when_active", table_name="boards", postgresql_where="is_active = true"
    )
    op.drop_table("boards")
    op.drop_index(op.f("ix_board_templates_game_id"), table_name="board_templates")
    op.drop_index(op.f("ix_board_templates_account_id"), table_name="board_templates")
    op.drop_table("board_templates")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_account_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_account_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_jam_code_redemptions_jam_code_id"), table_name="jam_code_redemptions")
    op.drop_index("ix_jam_code_redemptions_jam_code_account", table_name="jam_code_redemptions")
    op.drop_index(op.f("ix_jam_code_redemptions_account_id"), table_name="jam_code_redemptions")
    op.drop_table("jam_code_redemptions")
    op.drop_index(op.f("ix_games_slug"), table_name="games")
    op.drop_index(op.f("ix_games_account_id"), table_name="games")
    op.drop_table("games")
    op.drop_index(op.f("ix_verification_codes_expires_at"), table_name="verification_codes")
    op.drop_index("ix_verification_codes_email_status", table_name="verification_codes")
    op.drop_index(op.f("ix_verification_codes_email"), table_name="verification_codes")
    op.drop_table("verification_codes")
    op.drop_index(op.f("ix_jam_codes_code"), table_name="jam_codes")
    op.drop_index("ix_jam_codes_active_expires", table_name="jam_codes")
    op.drop_table("jam_codes")
    op.drop_index(op.f("ix_emails_to"), table_name="emails")
    op.drop_index(op.f("ix_emails_status"), table_name="emails")
    op.drop_index(op.f("ix_emails_provider_message_id"), table_name="emails")
    op.drop_index("ix_emails_created_at", table_name="emails")
    op.drop_table("emails")
    op.drop_index(op.f("ix_accounts_slug"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_name"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
