"""add scores table

Revision ID: e39a80493d94
Revises: f1c65a42d27c
Create Date: 2025-11-11 15:21:51.772112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39a80493d94'
down_revision: Union[str, Sequence[str], None] = 'f1c65a42d27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('value_display', sa.String(), nullable=True),
    sa.Column('filter_timezone', sa.String(), nullable=True),
    sa.Column('filter_country', sa.String(), nullable=True),
    sa.Column('filter_city', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_account_id'), 'scores', ['account_id'], unique=False)
    op.create_index(op.f('ix_scores_board_id'), 'scores', ['board_id'], unique=False)
    op.create_index(op.f('ix_scores_game_id'), 'scores', ['game_id'], unique=False)
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_game_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_board_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_account_id'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
