"""Add description to boards

Revision ID: 9e2b9374eb68
Revises: 8d64722e3661
Create Date: 2025-12-11 16:02:47.994341

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e2b9374eb68"
down_revision: str | Sequence[str] | None = "8d64722e3661"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boards", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boards", "description")
    # ### end Alembic commands ###
