"""add anti-cheat tables

Revision ID: 12b367f5d9da
Revises: afee0c496a21
Create Date: 2025-11-12 13:52:51.843841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b367f5d9da'
down_revision: Union[str, Sequence[str], None] = 'afee0c496a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_flags',
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('flag_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_decision', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_flags_confidence'), 'score_flags', ['confidence'], unique=False)
    op.create_index(op.f('ix_score_flags_flag_type'), 'score_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_score_flags_score_id'), 'score_flags', ['score_id'], unique=False)
    op.create_index(op.f('ix_score_flags_status'), 'score_flags', ['status'], unique=False)
    op.create_table('score_submission_metadata',
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('last_submission_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_submission_metadata_board_id'), 'score_submission_metadata', ['board_id'], unique=False)
    op.create_index(op.f('ix_score_submission_metadata_score_id'), 'score_submission_metadata', ['score_id'], unique=False)
    op.create_index(op.f('ix_score_submission_metadata_user_id'), 'score_submission_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_submission_metadata_user_id'), table_name='score_submission_metadata')
    op.drop_index(op.f('ix_score_submission_metadata_score_id'), table_name='score_submission_metadata')
    op.drop_index(op.f('ix_score_submission_metadata_board_id'), table_name='score_submission_metadata')
    op.drop_table('score_submission_metadata')
    op.drop_index(op.f('ix_score_flags_status'), table_name='score_flags')
    op.drop_index(op.f('ix_score_flags_score_id'), table_name='score_flags')
    op.drop_index(op.f('ix_score_flags_flag_type'), table_name='score_flags')
    op.drop_index(op.f('ix_score_flags_confidence'), table_name='score_flags')
    op.drop_table('score_flags')
    # ### end Alembic commands ###
