"""add score_metadata column

Revision ID: 32e23fb2cb23
Revises: dc2ab243348c
Create Date: 2025-11-13 18:07:31.899254

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "32e23fb2cb23"
down_revision: str | Sequence[str] | None = "dc2ab243348c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores", sa.Column("score_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "score_metadata")
    # ### end Alembic commands ###
