"""replace game name unique constraint with partial index excluding soft deletes

Revision ID: 4f4d897ebadb
Revises: 79ea935918b3
Create Date: 2026-02-04 18:13:14.756007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4d897ebadb'
down_revision: Union[str, Sequence[str], None] = '79ea935918b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_account_game_name'), 'games', type_='unique')
    op.create_index('ix_game_account_name_active', 'games', ['account_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_account_name_active', table_name='games', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_account_game_name'), 'games', ['account_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
