"""add unique_player_names to board_templates

Revision ID: c3f30ab1f058
Revises: 419a07d92b81
Create Date: 2026-08-17 10:52:07.522026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f30ab1f058'
down_revision: Union[str, Sequence[str], None] = '419a07d92b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_templates', sa.Column('unique_player_names', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_templates', 'unique_player_names')
    # ### end Alembic commands ###
