"""remove device sessions

Revision ID: 2ef130c5dca0
Revises: d551a65871fd
Create Date: 2026-01-26 09:46:13.265790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ef130c5dca0'
down_revision: Union[str, Sequence[str], None] = 'd551a65871fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_sessions_access_token_hash'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_device_id'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_expires_at'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_refresh_expires_at'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_refresh_token_hash'), table_name='device_sessions')
    op.drop_table('device_sessions')
    op.drop_column('identity_sessions', 'ip_address')
    op.drop_column('identity_sessions', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_sessions', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('identity_sessions', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('device_sessions',
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('refresh_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_sessions_device_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_sessions_pkey'))
    )
    op.create_index(op.f('ix_device_sessions_refresh_token_hash'), 'device_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_device_sessions_refresh_expires_at'), 'device_sessions', ['refresh_expires_at'], unique=False)
    op.create_index(op.f('ix_device_sessions_expires_at'), 'device_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_device_sessions_device_id'), 'device_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_sessions_access_token_hash'), 'device_sessions', ['access_token_hash'], unique=False)
    # ### end Alembic commands ###
