"""add_board_states_table

Revision ID: 96bea241843b
Revises: 1241eb4691bf
Create Date: 2026-01-23 09:53:48.105700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96bea241843b'
down_revision: Union[str, Sequence[str], None] = '1241eb4691bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_states',
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('primary_value', sa.Float(), nullable=True),
    sa.Column('aux', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'identity_id', name='uq_board_state_board_identity')
    )
    op.create_index(op.f('ix_board_states_board_id'), 'board_states', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_states_identity_id'), 'board_states', ['identity_id'], unique=False)
    op.create_index('ix_board_states_ranking', 'board_states', ['board_id', 'primary_value', 'updated_at', 'id'], unique=False, postgresql_where='deleted_at IS NULL AND primary_value IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_board_states_ranking', table_name='board_states', postgresql_where='deleted_at IS NULL AND primary_value IS NOT NULL')
    op.drop_index(op.f('ix_board_states_identity_id'), table_name='board_states')
    op.drop_index(op.f('ix_board_states_board_id'), table_name='board_states')
    op.drop_table('board_states')
    # ### end Alembic commands ###
