"""add_run_entries_table

Revision ID: d753d8fffd41
Revises: 96bea241843b
Create Date: 2026-01-23 10:14:12.789014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd753d8fffd41'
down_revision: Union[str, Sequence[str], None] = '96bea241843b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_entries',
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('score_event_id', sa.Uuid(), nullable=False),
    sa.Column('primary_value', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_event_id'], ['score_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'score_event_id', name='uq_run_entry_board_score_event')
    )
    op.create_index(op.f('ix_run_entries_board_id'), 'run_entries', ['board_id'], unique=False)
    op.create_index(op.f('ix_run_entries_identity_id'), 'run_entries', ['identity_id'], unique=False)
    op.create_index('ix_run_entries_ranking', 'run_entries', ['board_id', 'primary_value', 'created_at', 'id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_run_entries_score_event_id'), 'run_entries', ['score_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_entries_score_event_id'), table_name='run_entries')
    op.drop_index('ix_run_entries_ranking', table_name='run_entries', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_run_entries_identity_id'), table_name='run_entries')
    op.drop_index(op.f('ix_run_entries_board_id'), table_name='run_entries')
    op.drop_table('run_entries')
    # ### end Alembic commands ###
