"""add denormalized fields to board_states and run_entries

Revision ID: 40bf499fbfe0
Revises: 2ef130c5dca0
Create Date: 2026-01-26 11:21:00.739450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40bf499fbfe0'
down_revision: Union[str, Sequence[str], None] = '2ef130c5dca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_states', sa.Column('player_name', sa.String(), server_default='', nullable=False))
    op.add_column('board_states', sa.Column('is_test', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('board_states', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('board_states', sa.Column('country', sa.String(), nullable=True))
    op.add_column('board_states', sa.Column('city', sa.String(), nullable=True))
    op.add_column('board_states', sa.Column('value_display', sa.String(), nullable=True))
    op.add_column('board_states', sa.Column('state_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('run_entries', sa.Column('player_name', sa.String(), server_default='', nullable=False))
    op.add_column('run_entries', sa.Column('is_test', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('run_entries', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('run_entries', sa.Column('country', sa.String(), nullable=True))
    op.add_column('run_entries', sa.Column('city', sa.String(), nullable=True))
    op.add_column('run_entries', sa.Column('value_display', sa.String(), nullable=True))
    op.add_column('run_entries', sa.Column('entry_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_entries', 'entry_metadata')
    op.drop_column('run_entries', 'value_display')
    op.drop_column('run_entries', 'city')
    op.drop_column('run_entries', 'country')
    op.drop_column('run_entries', 'timezone')
    op.drop_column('run_entries', 'is_test')
    op.drop_column('run_entries', 'player_name')
    op.drop_column('board_states', 'state_metadata')
    op.drop_column('board_states', 'value_display')
    op.drop_column('board_states', 'city')
    op.drop_column('board_states', 'country')
    op.drop_column('board_states', 'timezone')
    op.drop_column('board_states', 'is_test')
    op.drop_column('board_states', 'player_name')
    # ### end Alembic commands ###
