"""Add pagination and filtering indices

Revision ID: b9d0a9c3ca38
Revises: 4f4d897ebadb
Create Date: 2026-02-18 13:03:17.821997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d0a9c3ca38'
down_revision: Union[str, Sequence[str], None] = '4f4d897ebadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_accounts_deleted_created', 'accounts', ['deleted_at', 'created_at', 'id'], unique=False)
    op.create_index('ix_accounts_deleted_name', 'accounts', ['deleted_at', 'name', 'id'], unique=False)
    op.create_index('ix_accounts_deleted_updated', 'accounts', ['deleted_at', 'updated_at', 'id'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index('ix_board_templates_account_deleted_created', 'board_templates', ['account_id', 'deleted_at', 'created_at', 'id'], unique=False)
    op.create_index('ix_board_templates_account_deleted_updated', 'board_templates', ['account_id', 'deleted_at', 'updated_at', 'id'], unique=False)
    op.create_index('ix_board_templates_account_game_deleted_created', 'board_templates', ['account_id', 'game_id', 'deleted_at', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_board_templates_is_active'), 'board_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_board_templates_next_run_at'), 'board_templates', ['next_run_at'], unique=False)
    op.create_index('ix_boards_account_deleted_created', 'boards', ['account_id', 'deleted_at', 'created_at', 'id'], unique=False)
    op.create_index('ix_boards_account_deleted_updated', 'boards', ['account_id', 'deleted_at', 'updated_at', 'id'], unique=False)
    op.create_index('ix_boards_account_game_deleted_created', 'boards', ['account_id', 'game_id', 'deleted_at', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_boards_created_from_template_id'), 'boards', ['created_from_template_id'], unique=False)
    op.create_index(op.f('ix_boards_is_active'), 'boards', ['is_active'], unique=False)
    op.create_index(op.f('ix_boards_is_published'), 'boards', ['is_published'], unique=False)
    op.create_index('ix_games_account_deleted_created', 'games', ['account_id', 'deleted_at', 'created_at', 'id'], unique=False)
    op.create_index('ix_games_account_deleted_name', 'games', ['account_id', 'deleted_at', 'name', 'id'], unique=False)
    op.create_index('ix_games_account_deleted_updated', 'games', ['account_id', 'deleted_at', 'updated_at', 'id'], unique=False)
    op.create_index('ix_users_account_deleted_created', 'users', ['account_id', 'deleted_at', 'created_at', 'id'], unique=False)
    op.create_index('ix_users_account_deleted_updated', 'users', ['account_id', 'deleted_at', 'updated_at', 'id'], unique=False)
    op.create_index(op.f('ix_users_is_owner'), 'users', ['is_owner'], unique=False)
    op.create_index(op.f('ix_users_super_admin'), 'users', ['super_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_super_admin'), table_name='users')
    op.drop_index(op.f('ix_users_is_owner'), table_name='users')
    op.drop_index('ix_users_account_deleted_updated', table_name='users')
    op.drop_index('ix_users_account_deleted_created', table_name='users')
    op.drop_index('ix_games_account_deleted_updated', table_name='games')
    op.drop_index('ix_games_account_deleted_name', table_name='games')
    op.drop_index('ix_games_account_deleted_created', table_name='games')
    op.drop_index(op.f('ix_boards_is_published'), table_name='boards')
    op.drop_index(op.f('ix_boards_is_active'), table_name='boards')
    op.drop_index(op.f('ix_boards_created_from_template_id'), table_name='boards')
    op.drop_index('ix_boards_account_game_deleted_created', table_name='boards')
    op.drop_index('ix_boards_account_deleted_updated', table_name='boards')
    op.drop_index('ix_boards_account_deleted_created', table_name='boards')
    op.drop_index(op.f('ix_board_templates_next_run_at'), table_name='board_templates')
    op.drop_index(op.f('ix_board_templates_is_active'), table_name='board_templates')
    op.drop_index('ix_board_templates_account_game_deleted_created', table_name='board_templates')
    op.drop_index('ix_board_templates_account_deleted_updated', table_name='board_templates')
    op.drop_index('ix_board_templates_account_deleted_created', table_name='board_templates')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index('ix_accounts_deleted_updated', table_name='accounts')
    op.drop_index('ix_accounts_deleted_name', table_name='accounts')
    op.drop_index('ix_accounts_deleted_created', table_name='accounts')
    # ### end Alembic commands ###
