"""add unique_player_names to boards

Revision ID: 419a07d92b81
Revises: 20f1e39f3c19
Create Date: 2026-08-11 12:58:54.381640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419a07d92b81'
down_revision: Union[str, Sequence[str], None] = '20f1e39f3c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_board_states_board_id_player_name_lower', 'board_states', ['board_id', sa.literal_column('lower(player_name)')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('boards', sa.Column('unique_player_names', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_run_entries_board_id_player_name_lower', 'run_entries', ['board_id', sa.literal_column('lower(player_name)')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_entries_board_id_player_name_lower', table_name='run_entries', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('boards', 'unique_player_names')
    op.drop_index('ix_board_states_board_id_player_name_lower', table_name='board_states', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
