"""Add user status and verification code type for invite flow

Revision ID: c0a5fa4bb6d6
Revises: 92b3a5ba6efe
Create Date: 2026-01-08 12:09:17.020556

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0a5fa4bb6d6"
down_revision: str | Sequence[str] | None = "92b3a5ba6efe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first (required for PostgreSQL)
    user_status = sa.Enum("INVITED", "ACTIVE", "SUSPENDED", name="user_status")
    user_status.create(op.get_bind())

    verification_code_type = sa.Enum("REGISTRATION", "INVITE", name="verification_code_type")
    verification_code_type.create(op.get_bind())

    op.add_column(
        "users", sa.Column("status", user_status, server_default="ACTIVE", nullable=False)
    )
    op.add_column(
        "verification_codes",
        sa.Column(
            "code_type", verification_code_type, server_default="REGISTRATION", nullable=False
        ),
    )
    op.add_column("verification_codes", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_verification_codes_type_user_id",
        "verification_codes",
        ["code_type", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_codes_user_id"), "verification_codes", ["user_id"], unique=False
    )
    op.create_foreign_key(
        None, "verification_codes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("verification_codes_user_id_fkey", "verification_codes", type_="foreignkey")
    op.drop_index(op.f("ix_verification_codes_user_id"), table_name="verification_codes")
    op.drop_index("ix_verification_codes_type_user_id", table_name="verification_codes")
    op.drop_column("verification_codes", "user_id")
    op.drop_column("verification_codes", "code_type")
    op.drop_column("users", "status")

    # Drop enum types
    sa.Enum(name="verification_code_type").drop(op.get_bind())
    sa.Enum(name="user_status").drop(op.get_bind())
    # ### end Alembic commands ###
