"""add excluded columns to run_entries

Revision ID: 79ea935918b3
Revises: cc4d01163cea
Create Date: 2026-01-27 11:43:21.524080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ea935918b3'
down_revision: Union[str, Sequence[str], None] = 'cc4d01163cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_entries', sa.Column('excluded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('run_entries', sa.Column('excluded_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_entries', 'excluded_reason')
    op.drop_column('run_entries', 'excluded_at')
    # ### end Alembic commands ###
