"""add is_test column to scores

Revision ID: d25522b75751
Revises: 554c52ba9114
Create Date: 2026-01-14 19:07:24.873993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d25522b75751"
down_revision: str | Sequence[str] | None = "554c52ba9114"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores", sa.Column("is_test", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "is_test")
    # ### end Alembic commands ###
