"""remove scores table

Revision ID: cc4d01163cea
Revises: 40bf499fbfe0
Create Date: 2026-01-26 14:28:01.389023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc4d01163cea'
down_revision: Union[str, Sequence[str], None] = '40bf499fbfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_account_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_board_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_device_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_game_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_ranking'), table_name='scores', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_scores_status'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('value_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filter_timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filter_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filter_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_test', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('provisional', 'active', 'under_review', 'rejected', name='score_status'), server_default=sa.text("'provisional'::score_status"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('scores_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('scores_board_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('scores_game_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scores_pkey'))
    )
    op.create_index(op.f('ix_scores_status'), 'scores', ['status'], unique=False)
    op.create_index(op.f('ix_scores_ranking'), 'scores', ['board_id', 'value', 'created_at', 'id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_scores_game_id'), 'scores', ['game_id'], unique=False)
    op.create_index(op.f('ix_scores_device_id'), 'scores', ['device_id'], unique=False)
    op.create_index(op.f('ix_scores_board_id'), 'scores', ['board_id'], unique=False)
    op.create_index(op.f('ix_scores_account_id'), 'scores', ['account_id'], unique=False)
    # ### end Alembic commands ###
