"""add_geo_fields_to_accounts

Revision ID: c31141498ab9
Revises: b9d0a9c3ca38
Create Date: 2026-03-17 11:09:52.916593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31141498ab9'
down_revision: Union[str, Sequence[str], None] = 'b9d0a9c3ca38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('country', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'city')
    op.drop_column('accounts', 'country')
    op.drop_column('accounts', 'timezone')
    # ### end Alembic commands ###
