"""Add is_owner column to users table

Revision ID: e49027eaf405
Revises: c0a5fa4bb6d6
Create Date: 2026-01-08 14:12:53.666329

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e49027eaf405"
down_revision: str | Sequence[str] | None = "c0a5fa4bb6d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_owner", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_owner")
    # ### end Alembic commands ###
