"""add_score_events_table

Revision ID: 1241eb4691bf
Revises: 86a8f50de7ed
Create Date: 2026-01-23 09:37:46.105448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1241eb4691bf'
down_revision: Union[str, Sequence[str], None] = '86a8f50de7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_events',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_events_account_id'), 'score_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_score_events_board_id'), 'score_events', ['board_id'], unique=False)
    op.create_index('ix_score_events_board_identity', 'score_events', ['board_id', 'identity_id'], unique=False)
    op.create_index(op.f('ix_score_events_game_id'), 'score_events', ['game_id'], unique=False)
    op.create_index(op.f('ix_score_events_identity_id'), 'score_events', ['identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_events_identity_id'), table_name='score_events')
    op.drop_index(op.f('ix_score_events_game_id'), table_name='score_events')
    op.drop_index('ix_score_events_board_identity', table_name='score_events')
    op.drop_index(op.f('ix_score_events_board_id'), table_name='score_events')
    op.drop_index(op.f('ix_score_events_account_id'), table_name='score_events')
    op.drop_table('score_events')
    # ### end Alembic commands ###
