services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    container_name: postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

  admin-api:
    extends:
      file: docker-compose.base.yml
      service: admin-api
    container_name: leadr-admin-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      ENV: DEV
      RUN_MIGRATIONS: "true"
    ports:
      - "8001:${PORT:-8000}"
    volumes:
      - ..:/app
      - /app/.venv
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    command: ./scripts/start.sh
    develop:
      watch:
        - action: rebuild
          path: ../uv.lock

  client-api:
    extends:
      file: docker-compose.base.yml
      service: client-api
    container_name: leadr-client-api
    depends_on:
      db:
        condition: service_healthy
      admin-api:
        condition: service_healthy
    environment:
      DB_HOST: db
      ENV: DEV
    ports:
      - "8000:${PORT:-8000}"
    volumes:
      - ..:/app
      - /app/.venv
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    command: ./scripts/start.sh
    develop:
      watch:
        - action: rebuild
          path: ../uv.lock

volumes:
  db_data:
