services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER:-leadr}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-leadr}
      PGDATA: /data/postgres
    volumes:
      - db_data:/data/postgres
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-leadr} -d ${DB_NAME:-leadr}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5332:5432"
    restart: unless-stopped

  admin-api:
    extends:
      file: docker-compose.base.yml
      service: admin-api
    container_name: leadr-admin-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      ENV: DEV
      RUN_MIGRATIONS: "true"
    ports:
      - "8001:${PORT:-8000}"
    volumes:
      - ..:/app
      - /app/.venv
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    command: ./scripts/start.sh
    develop:
      watch:
        - action: rebuild
          path: ../uv.lock

  client-api:
    extends:
      file: docker-compose.base.yml
      service: client-api
    container_name: leadr-client-api
    depends_on:
      db:
        condition: service_healthy
      admin-api:
        condition: service_healthy
    environment:
      DB_HOST: db
      ENV: DEV
    ports:
      - "8000:${PORT:-8000}"
    volumes:
      - ..:/app
      - /app/.venv
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    command: ./scripts/start.sh
    develop:
      watch:
        - action: rebuild
          path: ../uv.lock

volumes:
  db_data:
