version: 1
disable_existing_loggers: false

formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s.%(msecs)03d|{app}|{env}|server [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
    use_colors: true

  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: "%(asctime)s.%(msecs)03d|{app}|{env}|access [%(levelname)s] %(client_addr)s - \"%(request_line)s\" %(status_code)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
    use_colors: true

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout

  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: false

  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: false

  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: false
